version: '2.4'
services:
  antizapret-vpn:
    image: xtrime/antizapret-vpn:latest
    build: ./
    container_name: antizapret-vpn
    restart: unless-stopped
    ports:
      - "1194:1194/tcp"
      - "1194:1194/udp"
    volumes:
      - ./client_keys/:/root/easy-rsa-ipsec/CLIENT_KEY/
      - ./easyrsa3/:/root/easy-rsa-ipsec/easyrsa3/
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "1"
